# -*- coding: utf-8 -*-
"""EUREKA_SE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsNwJg7zcjnGLDzKN30Xtr82belCCmSy
"""

.0
# ==========================================
# EUREKA-SE • Information-Theoretic Analyzer
# Cell 1 – Setup & Sample Repository
# ==========================================

import os

# Create working folder
os.makedirs("sample_repo", exist_ok=True)

# --- sample_repo/user_v1.py ---
with open("sample_repo/user_v1.py", "w") as f:
    f.write("""
def get_user_name(uid):
    if uid == 1:
        return "Alice"
    elif uid == 2:
        return "Bob"
    else:
        return "Guest"
""")

# --- sample_repo/user_v2.py ---
with open("sample_repo/user_v2.py", "w") as f:
    f.write("""
def get_user_name(uid):
    if uid == 1:
        return "Alice"
    elif uid == 2:
        return "Bob"
    elif uid == 3:
        return "Charlie"
    else:
        return "Guest"

def get_user_role(uid):
    if uid == 1:
        return "Admin"
    elif uid == 2:
        return "Moderator"
    elif uid == 3:
        return "Viewer"
    else:
        return "Guest"
""")

# --- sample_repo/utils.py ---
with open("sample_repo/utils.py", "w") as f:
    f.write("""
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def add_numbers(a, b):  # redundant
    return a + b
""")

print("✅ Sample repository created successfully.")

# ==========================================
# Cell 2 – Core Functions (Tokenizer + Metrics)
# ==========================================

import re, math, gzip, json
from collections import Counter
import os

# --- Tokenization & Entropy ---
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|==|!=|<=|>=|->|:=|[-+*/%<>]=?|[:();,\.]|\d+")

def tokenize_code(code: str):
    return TOKEN_RE.findall(code)

def shannon_entropy(tokens):
    if not tokens: return 0.0
    n, counts = len(tokens), Counter(tokens)
    return -sum((c/n)*math.log2(c/n) for c in counts.values())

# --- Kolmogorov Complexity Approximation ---
def kc_ratio(code: str):
    if not code: return 0.0
    orig = len(code.encode())
    comp = len(gzip.compress(code.encode()))
    return comp / orig

# --- Mutual Information & KL Divergence ---
def mutual_info(a, b):
    if not a or not b: return 0.0
    ca, cb = Counter(a), Counter(b)
    na, nb = len(a), len(b)
    I = 0.0
    for k in set(ca)|set(cb):
        pa, pb = ca.get(k,0)/na, cb.get(k,0)/nb
        p_ab = (pa+pb)/2
        if p_ab>0:
            I += p_ab*math.log2((p_ab/(pa*pb+1e-12))+1e-12)
    return I

def kl_div(p, q):
    cp, cq = Counter(p), Counter(q)
    tp, tq = len(p), len(q)
    D = 0.0
    for k in set(cp)|set(cq):
        pk, qk = cp.get(k,0)/tp if tp else 0, cq.get(k,0)/tq if tq else 0
        pk, qk = max(pk,1e-12), max(qk,1e-12)
        D += pk*math.log2(pk/qk)
    return D

print("✅ Core analytical functions loaded.")

# ==========================================
# Cell 3 – Repository Analyzer
# ==========================================

def scan_repo(repo_path):
    py_files = []
    for root, _, files in os.walk(repo_path):
        for f in files:
            if f.endswith(".py"):
                py_files.append(os.path.join(root, f))
    return py_files

def analyze_repo(repo_path):
    result = {}
    for path in scan_repo(repo_path):
        code = open(path, encoding="utf-8").read()
        tokens = tokenize_code(code)
        result[path] = {
            "entropy": round(shannon_entropy(tokens), 3),
            "kc_ratio": round(kc_ratio(code), 3),
            "tokens": len(tokens)
        }
    return result

analysis = analyze_repo("sample_repo")
print(json.dumps(analysis, indent=2))

# ==========================================
# Cell 4 – CI/CD Guard Simulation
# ==========================================

def simulate_ci(base_tokens, head_tokens):
    H_base, H_head = shannon_entropy(base_tokens), shannon_entropy(head_tokens)
    delta = H_head - H_base
    Dkl = kl_div(head_tokens, base_tokens)
    print(f"Base entropy: {H_base:.2f}, Head entropy: {H_head:.2f}, ΔH={delta:.2f}, KL={Dkl:.2f}")
    if delta > 1.0:
        return "BLOCK ❌  –  High complexity increase"
    elif Dkl > 0.2:
        return "WARN ⚠️  –  Significant structural change"
    else:
        return "PASS ✅  –  Within limits"

# Load files and simulate
base = tokenize_code(open("sample_repo/user_v1.py").read())
head = tokenize_code(open("sample_repo/user_v2.py").read())
decision = simulate_ci(base, head)
print("CI/CD Decision:", decision)

# ==========================================
# Cell 5 – Summary & Visualization
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt

# Convert analysis dict to DataFrame
df = pd.DataFrame(analysis).T
display(df)

# --- Entropy bar chart ---
plt.figure(figsize=(6,4))
plt.bar(df.index.map(lambda x: os.path.basename(x)), df['entropy'], color='skyblue')
plt.title("Entropy of Repository Files")
plt.ylabel("Entropy (bits)")
plt.show()

# --- KC ratio bar chart ---
plt.figure(figsize=(6,4))
plt.bar(df.index.map(lambda x: os.path.basename(x)), df['kc_ratio'], color='salmon')
plt.title("Kolmogorov Complexity Ratios")
plt.ylabel("Compression Ratio")
plt.show()